/**
 * Collect release artifacts from every `src-tauri/target/<triple>/release/bundle` tree into:
 * - release/windows  (installers + windows updater archive/signature)
 * - release/macos    (installers + mac updater archive/signature)
 * - release/updates  (latest.json + all updater payloads/signatures for website upload)
 *
 * Artifacts are renamed to STABLE filenames so the website download links and the
 * URLs inside latest.json never change between releases — you just overwrite the
 * files in the BlueSync.education storage bucket and replace latest.json.
 *
 * latest.json is GENERATED by this script (version from tauri.conf.json, signatures
 * from the .sig files Tauri emits when TAURI_SIGNING_PRIVATE_KEY is set). If a
 * latest.json already exists in release/updates it is merged, so running this once
 * on Windows and once on a Mac accumulates all platforms into one manifest.
 *
 * Override the download host with the RELEASE_DOWNLOAD_BASE_URL env var.
 */
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

/** Public base URL of the `releases` storage bucket on BlueSync.education (Lovable Cloud). */
const DOWNLOAD_BASE_URL = (
  process.env.RELEASE_DOWNLOAD_BASE_URL ??
  "https://otfbgtdtzlfvjmohpacm.supabase.co/storage/v1/object/public/releases"
).replace(/\/+$/, "");

/** Stable artifact names per `platform-arch` updater key. */
const STABLE_NAMES = {
  "windows-x86_64": {
    exe: "BlueSync-Student-Setup.exe",
    msi: "BlueSync-Student-Setup.msi",
    updater: "BlueSync-Student-update-windows-x86_64.nsis.zip",
  },
  "darwin-aarch64": {
    dmg: "BlueSync-Student.dmg",
    updater: "BlueSync-Student-update-darwin-aarch64.app.tar.gz",
  },
  "darwin-x86_64": {
    dmg: "BlueSync-Student-Intel.dmg",
    updater: "BlueSync-Student-update-darwin-x86_64.app.tar.gz",
  },
};

function readAppVersion() {
  const conf = JSON.parse(
    fs.readFileSync(path.join(root, "src-tauri", "tauri.conf.json"), "utf8"),
  );
  return conf.version;
}

function hostPlatformKey() {
  const arch = process.arch === "arm64" ? "aarch64" : "x86_64";
  if (process.platform === "darwin") return `darwin-${arch}`;
  if (process.platform === "win32") return `windows-${arch}`;
  return `linux-${arch}`;
}

/** Map a rust target triple (from the target dir name) to an updater platform key. */
function tripleToPlatformKey(dirName) {
  const m = /^(x86_64|aarch64|arm64|i686)-/.exec(dirName);
  if (!m) return null;
  const arch = m[1] === "arm64" ? "aarch64" : m[1];
  if (dirName.includes("apple-darwin")) return `darwin-${arch}`;
  if (dirName.includes("windows")) return `windows-${arch}`;
  if (dirName.includes("linux")) return `linux-${arch}`;
  return null;
}

function discoverBundleRoots() {
  const targetDir = path.join(root, "src-tauri", "target");
  const roots = [];
  const legacy = path.join(targetDir, "release", "bundle");
  if (fs.existsSync(legacy)) roots.push({ dir: legacy, platformKey: hostPlatformKey() });
  if (fs.existsSync(targetDir)) {
    for (const name of fs.readdirSync(targetDir)) {
      const b = path.join(targetDir, name, "release", "bundle");
      const platformKey = tripleToPlatformKey(name);
      if (platformKey && fs.existsSync(b)) roots.push({ dir: b, platformKey });
    }
  }
  return roots;
}

const destWin = path.join(root, "release", "windows");
const destMac = path.join(root, "release", "macos");
const destUpdates = path.join(root, "release", "updates");

for (const dir of [destWin, destMac, destUpdates]) {
  fs.mkdirSync(dir, { recursive: true });
}

function walkFiles(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    if (st.isDirectory()) out.push(...walkFiles(p));
    else out.push(p);
  }
  return out;
}

let copied = 0;

function copyAs(src, destDir, stableName, label) {
  const dest = path.join(destDir, stableName);
  fs.copyFileSync(src, dest);
  console.log(`→ ${label}${stableName}  (from ${path.basename(src)})`);
  copied++;
  return dest;
}

const bundleRoots = discoverBundleRoots();
if (bundleRoots.length === 0) {
  console.warn("No bundle directories found under src-tauri/target — run npm run tauri:build first.");
  process.exit(1);
}
console.log("Scanning bundle roots:", bundleRoots.map((r) => `${r.dir} [${r.platformKey}]`).join(" | "));

const version = readAppVersion();
/** platformKey -> { url, signature } discovered during collection */
const platformEntries = {};

for (const { dir: bundleRoot, platformKey } of bundleRoots) {
  const names = STABLE_NAMES[platformKey];
  if (!names) {
    console.warn(`Skipping unsupported platform ${platformKey} at ${bundleRoot}`);
    continue;
  }

  // Old builds (other product names / versions) linger in target/release/bundle,
  // so only consider artifacts whose filename carries the current version, and
  // take the newest one if several match.
  const candidates = { exe: [], msi: [], dmg: [], updater: [] };
  for (const filePath of walkFiles(bundleRoot)) {
    const base = path.basename(filePath);
    const lower = base.toLowerCase();
    if (!base.includes(version)) continue;

    if (lower.endsWith(".exe")) candidates.exe.push(filePath);
    else if (lower.endsWith(".msi")) candidates.msi.push(filePath);
    else if (lower.endsWith(".dmg")) candidates.dmg.push(filePath);
    else if (lower.endsWith(".nsis.zip") || lower.endsWith(".app.tar.gz")) candidates.updater.push(filePath);
  }

  const newest = (files) =>
    files.length === 0
      ? null
      : files.reduce((a, b) => (fs.statSync(a).mtimeMs >= fs.statSync(b).mtimeMs ? a : b));

  for (const kind of ["exe", "msi", "dmg"]) {
    const stableName = names[kind];
    const src = newest(candidates[kind]);
    if (!stableName || !src) continue;
    copyAs(src, kind === "dmg" ? destMac : destWin, stableName, kind === "dmg" ? "release/macos/" : "release/windows/");
  }

  const updaterSrc = newest(candidates.updater);
  if (updaterSrc) {
    const isWin = updaterSrc.toLowerCase().endsWith(".nsis.zip");
    copyAs(updaterSrc, isWin ? destWin : destMac, names.updater, isWin ? "release/windows/" : "release/macos/");
    copyAs(updaterSrc, destUpdates, names.updater, "release/updates/");

    const sigPath = `${updaterSrc}.sig`;
    if (fs.existsSync(sigPath)) {
      copyAs(sigPath, destUpdates, `${names.updater}.sig`, "release/updates/");
      platformEntries[platformKey] = {
        signature: fs.readFileSync(sigPath, "utf8").trim(),
        url: `${DOWNLOAD_BASE_URL}/${names.updater}`,
      };
    } else {
      console.warn(
        `No .sig next to ${path.basename(updaterSrc)} — build with TAURI_SIGNING_PRIVATE_KEY set ` +
          "(npm run tauri:build:updater) or the updater cannot verify this release.",
      );
    }
  }

  const macosDir = path.join(bundleRoot, "macos");
  if (fs.existsSync(macosDir)) {
    for (const name of fs.readdirSync(macosDir)) {
      if (!name.endsWith(".app")) continue;
      const src = path.join(macosDir, name);
      const dest = path.join(destMac, name);
      fs.rmSync(dest, { recursive: true, force: true });
      fs.cpSync(src, dest, { recursive: true });
      console.log("→ release/macos/", `${name}/`);
      copied++;
    }
  }
}

if (copied === 0) {
  console.warn("No release artifacts matched filters under bundle roots.");
  process.exit(1);
}

// Generate (or merge into) the updater manifest served at
// https://bluesync.education/updates/latest.json
const manifestPath = path.join(destUpdates, "latest.json");
let manifest = { version, notes: "", pub_date: new Date().toISOString(), platforms: {} };
if (fs.existsSync(manifestPath)) {
  try {
    const existing = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    // Keep platforms from a previous run only if it was for the same version
    // (e.g. Windows artifacts collected before running this on a Mac).
    if (existing.version === version && existing.platforms) {
      manifest.platforms = existing.platforms;
    }
  } catch {
    /* regenerate from scratch */
  }
}
Object.assign(manifest.platforms, platformEntries);

// Manifest at https://bluesync.education/updates/latest.json must point at a URL that returns 200.
const websiteRoot = path.join(root, "..", "BlueSync Website");
const websiteUpdatesDir = path.join(websiteRoot, "public", "updates");
const websiteBase = (
  process.env.RELEASE_WEBSITE_BASE_URL ?? "https://bluesync.education"
).replace(/\/+$/, "");
const winEntry = manifest.platforms["windows-x86_64"];

if (winEntry?.signature) {
  const websiteZipName = `BlueSync-Student_${version}_x64-setup.nsis.zip`;
  const websiteUpdateUrl = `${websiteBase}/updates/${websiteZipName}`;
  const localUpdaterZip = path.join(destUpdates, STABLE_NAMES["windows-x86_64"].updater);

  manifest.platforms["windows-x86_64"] = {
    signature: winEntry.signature,
    url: websiteUpdateUrl,
  };

  if (fs.existsSync(websiteRoot)) {
    fs.mkdirSync(websiteUpdatesDir, { recursive: true });
    if (fs.existsSync(localUpdaterZip)) {
      fs.copyFileSync(localUpdaterZip, path.join(websiteUpdatesDir, websiteZipName));
      console.log(`→ BlueSync Website/public/updates/${websiteZipName}`);
    }
    fs.writeFileSync(
      path.join(websiteUpdatesDir, "latest.json"),
      `${JSON.stringify(manifest, null, 2)}\n`,
    );
    console.log("→ BlueSync Website/public/updates/latest.json");
  }

  if (platformEntries["windows-x86_64"]?.url?.includes("supabase")) {
    fs.writeFileSync(
      path.join(destUpdates, "latest-bucket.json"),
      `${JSON.stringify(
        {
          ...manifest,
          platforms: {
            ...manifest.platforms,
            "windows-x86_64": platformEntries["windows-x86_64"],
          },
        },
        null,
        2,
      )}\n`,
    );
    console.log("→ release/updates/latest-bucket.json  (Supabase — only after bucket upload works)");
  }
}

fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`→ release/updates/latest.json  (v${version}, platforms: ${Object.keys(manifest.platforms).join(", ") || "none"})`);

console.log("");
console.log("Done. Copied", copied, "item(s).");
console.log("1. Deploy BlueSync Website: public/updates/latest.json + .nsis.zip to bluesync.education");
console.log(`2. Optional Supabase bucket: ${DOWNLOAD_BASE_URL} (use latest-bucket.json only if zip URL returns 200)`);
console.log("");
console.log("IMPORTANT: signature = base64 from .sig file. Zip URL in latest.json must return HTTP 200.");
