// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otfbgtdtzlfvjmohpacm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90ZmJndGR0emxmdmptb2hwYWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTk0MDYsImV4cCI6MjA3MDQ5NTQwNn0.2HLrQxMeYrwF34nu2ZUFWbqyDhW4afIK4dOOOmomwA4";

/** Get current student user id from sessionStorage for RLS (custom auth). */
function getAppUserId(): string | null {
  try {
    const raw = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem('student_user') : null;
    if (!raw) return null;
    const user = JSON.parse(raw) as { id?: string };
    return user?.id ?? null;
  } catch {
    return null;
  }
}

/** Custom fetch so RLS current_user_id() can read x-app-user-id (student app uses custom login). */
const customFetch: typeof fetch = (input, init) => {
  const url = typeof input === 'string' ? input : input instanceof Request ? input.url : String(input);
  const opts = { ...init } as RequestInit;
  const headers = new Headers(opts.headers);
  const uid = getAppUserId();
  if (uid) headers.set('x-app-user-id', uid);
  opts.headers = headers;
  return fetch(input, opts);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customFetch,
  },
});
