// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otfbgtdtzlfvjmohpacm.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90ZmJndGR0emxmdmptb2hwYWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTk0MDYsImV4cCI6MjA3MDQ5NTQwNn0.2HLrQxMeYrwF34nu2ZUFWbqyDhW4afIK4dOOOmomwA4";
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_ANON_KEY;

export { SUPABASE_URL };

/** Student identity is proven via session_token on RPCs — not x-app-user-id headers. */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
